# Retro CRT Theme for Kitty (Neovim Retro match)

foreground #fafab9
cursor #c7c7a5
selection_background #33332b
selection_foreground #ffffff

# Normal colors
color0  #1a1a19
color1  #a1683c
color2  #7fa86e
color3  #e6d97a
color4  #6c8495
color5  #957f9c
color6  #7fa89a
color7  #c7c7a5

# Bright colors
color8  #33332b
color9  #c47a44
color10 #99c67c
color12 #88a0b6
color13 #b498b5
color14 #99c6b1
color15 #ecebd4

